import type { Metadata } from "next";
import ConvexClientProvider from "./_components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <>{children} </>
      // <div>
      //   <ClerkProvider dynamic>
      //     <ConvexClientProvider>{children}</ConvexClientProvider>
      //   </ClerkProvider>
      // </div>
  );
}
